### ISSUE TITLE
Why can't create an entity?

### ISSUE THREAD

**Issue by chobits102** [jpoullet2000/atlasclient#106]
Why can't create an entity?
Only entities can be deleted

Nor can you create or delete typeDefs
Report errors:
atlasclient.exceptions.NotFound: HTTP request failed for DELETE http://127.0.0.1:21000/api/atlas/v2/types/typedefs: Not found 404: {"errorCode":"ATLAS-404-00-001","errorMessage":"Given typename test_entity_7 was invalid"}

**Comment by pritampan** [comment]
Hello @chobits102 , Can you please give more details like how you are actually using this library in the code. I am using `client.entity_post.create(data=entity_dict)` and `client.entity_bulk.create(data={"entities": entities})`. And both are working as expected.

Also create and delete typeDefs are working. Please refer the below code snippet.

```from atlasclient.client import Atlas
client = Atlas(host='localhost', port='80', username='admin', password='admin', timeout=10000)

typedef_dict = {
  "entityDefs": [
    {
      "category": "ENTITY",
      "name": "sample_entity_def",
      "description": "sample_entity_def",
      "typeVersion": "1.2",
      "serviceType": "rdbms",
      "attributeDefs": [

      ],
      "superTypes": [
        "DataSet"
      ],
      "subTypes": [

      ],
      "relationshipAttributeDefs": [
      ]
    }
  ]
}

client.typedefs.create(data=typedef_dict)

#client.typedefs.delete(data=typedef_dict)

**Comment by chobits102** [comment]
Thank you so much@pritampan, Run successfully based on your code, 
In addition, there is another question that needs your help.
How to know the necessary parameters and values?

**Comment by chobits102** [comment]
for example
                
{
  "entity" : {
    "classifications" : [ {
      "entityGuid" : "...",
      "entityStatus" : "DELETED",
      "propagate" : true,
      "removePropagationsOnEntityDelete" : true,
      "validityPeriods" : [ { }, { } ],
      "attributes" : {
        "property1" : { },
        "property2" : { }
      },
      "typeName" : "..."
    }, {
      "entityGuid" : "...",
      "entityStatus" : "ACTIVE",
      "propagate" : true,
      "removePropagationsOnEntityDelete" : true,
      "validityPeriods" : [ { }, { } ],
      "attributes" : {
        "property1" : { },
        "property2" : { }
      },
      "typeName" : "..."
    } ],
    "createTime" : 12345,
    "createdBy" : "...",
    "guid" : "...",
    "homeId" : "...",
    "meanings" : [ {
      "confidence" : 12345,
      "createdBy" : "...",
      "description" : "...",
      "displayText" : "...",
      "expression" : "...",
      "relationGuid" : "...",
      "source" : "...",
      "status" : "OTHER",
      "steward" : "...",
      "termGuid" : "..."
    }, {
      "confidence" : 12345,
      "createdBy" : "...",
      "description" : "...",
      "displayText" : "...",
      "expression" : "...",
      "relationGuid" : "...",
      "source" : "...",
      "status" : "OBSOLETE",
      "steward" : "...",
      "termGuid" : "..."
    } ],
    "provenanceType" : 12345,
    "proxy" : true,
    "relationshipAttributes" : {
      "property1" : { },
      "property2" : { }
    },
    "status" : "ACTIVE",
    "updateTime" : 12345,
    "updatedBy" : "...",
    "version" : 12345,
    "attributes" : {
      "property1" : { },
      "property2" : { }
    },
    "typeName" : "..."
  },
  "referredEntities" : {
    "property1" : {
      "classifications" : [ {
        "entityGuid" : "...",
        "entityStatus" : "DELETED",
        "propagate" : true,
        "removePropagationsOnEntityDelete" : true,
        "validityPeriods" : [ { }, { } ],
        "attributes" : {
          "property1" : { },
          "property2" : { }
        },
        "typeName" : "..."
      }, {
        "entityGuid" : "...",
        "entityStatus" : "DELETED",
        "propagate" : true,
        "removePropagationsOnEntityDelete" : true,
        "validityPeriods" : [ { }, { } ],
        "attributes" : {
          "property1" : { },
          "property2" : { }
        },
        "typeName" : "..."
      } ],
      "createTime" : 12345,
      "createdBy" : "...",
      "guid" : "...",
      "homeId" : "...",
      "meanings" : [ {
        "confidence" : 12345,
        "createdBy" : "...",
        "description" : "...",
        "displayText" : "...",
        "expression" : "...",
        "relationGuid" : "...",
        "source" : "...",
        "status" : "IMPORTED",
        "steward" : "...",
        "termGuid" : "..."
      }, {
        "confidence" : 12345,
        "createdBy" : "...",
        "description" : "...",
        "displayText" : "...",
        "expression" : "...",
        "relationGuid" : "...",
        "source" : "...",
        "status" : "DISCOVERED",
        "steward" : "...",
        "termGuid" : "..."
      } ],
      "provenanceType" : 12345,
      "proxy" : true,
      "relationshipAttributes" : {
        "property1" : { },
        "property2" : { }
      },
      "status" : "DELETED",
      "updateTime" : 12345,
      "updatedBy" : "...",
      "version" : 12345,
      "attributes" : {
        "property1" : { },
        "property2" : { }
      },
      "typeName" : "..."
    },
    "property2" : {
      "classifications" : [ {
        "entityGuid" : "...",
        "entityStatus" : "DELETED",
        "propagate" : true,
        "removePropagationsOnEntityDelete" : true,
        "validityPeriods" : [ { }, { } ],
        "attributes" : {
          "property1" : { },
          "property2" : { }
        },
        "typeName" : "..."
      }, {
        "entityGuid" : "...",
        "entityStatus" : "ACTIVE",
        "propagate" : true,
        "removePropagationsOnEntityDelete" : true,
        "validityPeriods" : [ { }, { } ],
        "attributes" : {
          "property1" : { },
          "property2" : { }
        },
        "typeName" : "..."
      } ],
      "createTime" : 12345,
      "createdBy" : "...",
      "guid" : "...",
      "homeId" : "...",
      "meanings" : [ {
        "confidence" : 12345,
        "createdBy" : "...",
        "description" : "...",
        "displayText" : "...",
        "expression" : "...",
        "relationGuid" : "...",
        "source" : "...",
        "status" : "DEPRECATED",
        "steward" : "...",
        "termGuid" : "..."
      }, {
        "confidence" : 12345,
        "createdBy" : "...",
        "description" : "...",
        "displayText" : "...",
        "expression" : "...",
        "relationGuid" : "...",
        "source" : "...",
        "status" : "DISCOVERED",
        "steward" : "...",
        "termGuid" : "..."
      } ],
      "provenanceType" : 12345,
      "proxy" : true,
      "relationshipAttributes" : {
        "property1" : { },
        "property2" : { }
      },
      "status" : "ACTIVE",
      "updateTime" : 12345,
      "updatedBy" : "...",
      "version" : 12345,
      "attributes" : {
        "property1" : { },
        "property2" : { }
      },
      "typeName" : "..."
    }
  }
}
                
              `

Founds the single entity, needs the such multi parameters and the value	
Don't understand

**Comment by pritampan** [comment]
Hello @chobits102 , for these details you have to go through the Apache Atlas documentation. For example 'hive_database', 'hive_table' or rdbms_table are of AtlasEntityWithExtInfo type which is documented [here](https://atlas.apache.org/api/v2/json_AtlasEntityWithExtInfo.html).

Hope this helps. Thanks!

**Comment by chobits102** [comment]
@pritampan Very helpful, Thanks!
