### ISSUE TITLE
Kerberos login support

### ISSUE THREAD

**Issue by dimon222** [jpoullet2000/atlasclient#42]
There's an auth module for requests that can make this happen. Any chance atlasclient can get support of switching auth to kerberos?
https://github.com/requests/requests-kerberos

**Comment by jpoullet2000** [comment]
Hi dimon22... it is indeed certainly an interesting/important feature to have for this client. Probably a few modifs in the [request method](https://github.com/jpoullet2000/atlasclient/blob/68fb8a6ea3a9033f019e24fa61b439cb592be82b/atlasclient/client.py#L131-L177) should make it work. However, I'd like to test it in a real env with a kerberized atlas before pushing. So far, I'm mocking all the requests. Would you agree to test it in a real environment? Another way would be to set up a true Hadoop + Kerberized Atlas env when testing... if you have any suggestion about it I'd be interested as well.

**Comment by dimon222** [comment]
@jpoullet2000  I gave it a look, and I think there's even easier way. Potentially requests.Session object allows auth attribute to be set to switch auth globally for all requests done with it.
http://docs.python-requests.org/en/master/api/#requests.Session.auth

If we just plug new auth in Session after instantiating Session in constructor of HttpClient, that should be it!
https://github.com/jpoullet2000/atlasclient/blob/68fb8a6ea3a9033f019e24fa61b439cb592be82b/atlasclient/client.py#L127

I'll give it a try in kerberized environment.

**Comment by jpoullet2000** [comment]
Thanks Dmitry. I'd be glad to accept your pull request.


Le jeu. 15 nov. 2018 à 04:15, Dmitry Romanenko <notifications@github.com> a
écrit :
