### ISSUE TITLE
Implement saved search

### ISSUE THREAD

**Issue by verdan** [jpoullet2000/atlasclient#81]
https://atlas.apache.org/api/v2/resource_DiscoveryREST.html#resource_DiscoveryREST_getSavedSearches_GET

**Comment by pritampan** [comment]
Hello @verdan , @jpoullet2000 , can I start working on this if you haven't started yet? Thanks

**Comment by verdan** [comment]
That would be awesome 😎!! Appreciated @pritampan

**Comment by pritampan** [comment]
Thanks a lot, I will start working on it.

**Comment by jpoullet2000** [comment]
@pritampan  Yes indeed. Very appreciated !
