### ISSUE TITLE
atlas_client.entity_post.create() do not return any result

### ISSUE THREAD

**Issue by Nyna71** [jpoullet2000/atlasclient#9]
It would nice if the entity_post.create() method returns at least the REST return code (f.e 204) from the Atlas API, as without response we have no clue if the entity has been created or not.

Ideally, we should be able to get back a kind of HTTP Response object, where we can extract the HTTP response as well as the body, which will give us the created GUID of the entity.

**Comment by jpoullet2000** [comment]
Corrected in the new release 0.1.2 (see 68fb8a6ea3a9033f019e24fa61b439cb592be82b). It returns now the json as returned by the atlas server.
